package com.woniuxy.domain;

public class Nation {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nation.CODE
     *
     * @mbggenerated Mon Aug 12 21:49:09 CST 2019
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nation.NATION
     *
     * @mbggenerated Mon Aug 12 21:49:09 CST 2019
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nation.spell
     *
     * @mbggenerated Mon Aug 12 21:49:09 CST 2019
     */
    private String spell;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column nation.simplespell
     *
     * @mbggenerated Mon Aug 12 21:49:09 CST 2019
     */
    private String simplespell;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nation.CODE
     *
     * @return the value of nation.CODE
     *
     * @mbggenerated Mon Aug 12 21:49:09 CST 2019
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nation.CODE
     *
     * @param code the value for nation.CODE
     *
     * @mbggenerated Mon Aug 12 21:49:09 CST 2019
     */
    public void setCode(String code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nation.NATION
     *
     * @return the value of nation.NATION
     *
     * @mbggenerated Mon Aug 12 21:49:09 CST 2019
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nation.NATION
     *
     * @param nation the value for nation.NATION
     *
     * @mbggenerated Mon Aug 12 21:49:09 CST 2019
     */
    public void setNation(String nation) {
        this.nation = nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nation.spell
     *
     * @return the value of nation.spell
     *
     * @mbggenerated Mon Aug 12 21:49:09 CST 2019
     */
    public String getSpell() {
        return spell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nation.spell
     *
     * @param spell the value for nation.spell
     *
     * @mbggenerated Mon Aug 12 21:49:09 CST 2019
     */
    public void setSpell(String spell) {
        this.spell = spell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column nation.simplespell
     *
     * @return the value of nation.simplespell
     *
     * @mbggenerated Mon Aug 12 21:49:09 CST 2019
     */
    public String getSimplespell() {
        return simplespell;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column nation.simplespell
     *
     * @param simplespell the value for nation.simplespell
     *
     * @mbggenerated Mon Aug 12 21:49:09 CST 2019
     */
    public void setSimplespell(String simplespell) {
        this.simplespell = simplespell;
    }
}